[build.environment]
  HUGO_VERSION = "0.156.0"
  HUGO_EXTENDED = "true"
  YARN_VERSION = "1.22.22"
  NPM_VERSION = "10.9.2"
  NODE_VERSION = "22"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
