[build.environment]
  HUGO_VERSION = "0.156.0"
  YARN_VERSION = "1.22.22"
  NPM_VERSION = "10.9.2"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
