[build.environment]
  HUGO_VERSION = "0.156.0"
  HUGO_EXTENDED = "true"
  YARN_VERSION = "1.22.22"
  NPM_VERSION = "10.9.2"
  NODE_VERSION = "22"
  NODE_OPTIONS = "--openssl-legacy-provider"

[build]
  command = "node_modules/.bin/tailwindcss -i site/themes/tella/assets/css/style.css -o site/static/css/tella.css --minify && yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "node_modules/.bin/tailwindcss -i site/themes/tella/assets/css/style.css -o site/static/css/tella.css --minify && yarn build:preview"
