baseURL = "https://www.melders.ru/"
title = "Актер Роман Мелдерс"
author = "Ivan Kozlov"
languageCode = "ru-ru"
DefaultContentLanguage = "ru"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

[services]
  [services.googleAnalytics]
    id = "G-PHBR4V8JVL"

  [services.disqus]
    shortname = "melders"

[params]
  showBlog = true
  mainSections = ['post']
  googleFonts = true

  [params.logo]
#    main = "images/avatar1.jpg"
#    alt = "Роман Мелдерс"
#    size = "h-12"

  [params.site]
    name = "Роман Мелдерс"

  [params.icon]
    bootstrap = false

  [params.homepage_meta_tags]
    meta_description = "Маленький актер с большими амбициями."
    meta_og_title = "Актер Роман Мелдерс"
    meta_og_type = "website"
    meta_og_url = "https://www.melders.ru"
    meta_og_image = "https://www.melders.ru/images/og_image.jpg"
    meta_og_description = "Маленький актер с большими амбициями."
    meta_twitter_card = "summary_large_image"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Биография"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "archives"
    name = "Портфолио"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "regalies"
    name = "Регалии"
    url = "/regalies/"
    weight = 3

  [[menu.main]]
    identifier = "photo"
    name = "Фото"
    url = "/photo/"
    weight = 4

  [[menu.main]]
    identifier = "post"
    name = "Блог"
    url = "/post/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "ВКонтакте"
    url = "https://vk.com/roman.melders"
    weight = 2

  [[menu.footer]]
    name = "Кинолифт"
    url = "https://kinolift.ru/16742"
    weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
